services:
  app:
    build:
      context: .
      dockerfile: dev.dockerfile
      args:
        - USER_ID=1000
        - GROUP_ID=1000
    ports:
      - 3000:3000
    volumes:
      - ".:/app"
    env_file:
      - ./.env
    command: ["run", "start:dev"]
    depends_on:
      - postgres
  postgres:
    image: "postgres:17"
    env_file:
      - ./.env
    ports:
      - '7000:5432'