services:
  app:
    build:
      context: .
      dockerfile: dev.dockerfile
      args:
        - USER_ID=1000
        - GROUP_ID=1000
    ports:
      - 3000:3000
    volumes:
      - ".:/app"
    env_file:
      - ./.env
    depends_on:
      - postgres
  postgres:
    image: "postgres:17"
    env_file:
      - ./.env
    ports:
      - '7000:5432'
    volumes:
      - pg_nuven:/var/lib/postgresql/data
  npm:
    build:
      context: .
      dockerfile: npm.dockerfile
      args:
        - USER_ID=1000
        - GROUP_ID=1000
    command: ["audit"]
    volumes:
      - ".:/app"
    env_file:
      - ./.env
volumes:
  pg_nuven: